### ISSUE TITLE
Fixed Redux issue.

### ISSUE THREAD

**Issue by dovy** [slavamak/wordpress-startup-template#1]
Dude, this package is pretty nice. I hope you finish it off. Good job.

To get Redux working you _must_ use Redux 4 as we've solved this issue there.

Here's your new composer file:
```json
{
	"name": "slavamak/wordpress-startup-template",
	"description": "Startup template for Wordpress development",
	"repositories":[
		{
			"type":"composer",
			"url":"https://wpackagist.org"
		},
		{
			"type": "vcs",
			"url":  "git@github.com:reduxframework/redux-framework-4.git"
		}
	],
	"require": {
		"php": ">=5.6",
		"johnpbloch/wordpress": "*",
		"wpackagist-plugin/cyr2lat": "*",
		"wpackagist-plugin/wordpress-seo": "*",
		"wpackagist-plugin/advanced-custom-fields": "*",
		"reduxframework/redux-framework-4": "dev-master",
		"wpackagist-plugin/contact-form-7": "*"
	},
	"extra": {
		"wordpress-install-dir": "web/core",
		"installer-paths": {
			"web/app/plugins/{$name}/": ["vendor:wpackagist-plugin"],
			"web/app/plugins/{$name}/": ["vendor:reduxframework"],
			"web/app/themes/{$name}/": ["vendor:wpackagist-theme"]
		}
	}
}
```

Now go activate Redux and you will have zero problems.  :)

**Comment by slavamak** [comment]
Wow Dovy , thanks for the quick response and a good assessment of my project :) I made corrections to composer.json by your example, I started the project, I activated Redux, but I still don’t have the save in the customizer. Maybe I'm doing something wrong?
![screenshot_2](https://user-images.githubusercontent.com/28267670/54044918-38543300-41e1-11e9-8a81-f5a2f46aa876.png)

**Comment by dovy** [comment]
This is where context is really useful. Now I see the issue is with the customizer and not the option panel. I’m on it.

**Comment by dovy** [comment]
Run your composer again. This has been resolved.  ;)
